replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

#imagePullSecrets: 
 # name: "gcp-artifact-registry-credentials"

service:
  type: ClusterIP
  port: 80



ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-artemis.zenithcst.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.zenithcst.net
